f = [-3; 1; 1];
A = [1, -2, 1;
     4, -1, -2];
b = [11; -3];
Aeq = [-2, 0, 1];
beq = 1;
lb = [0; 0; 0];
[x, fval] = linprog(f, A, b, Aeq, beq, lb);
fprintf('最优解：\n');
fprintf('x1 = %.4f\n', x(1));
fprintf('x2 = %.4f\n', x(2));
fprintf('x3 = %.4f\n', x(3));
fprintf('目标函数的最优值 z = %.4f\n', -fval); 